FROM golang:1.25-alpine AS build

RUN apk add --no-cache git

WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -trimpath -ldflags="-s -w" -o /forgejo-runner-k8s .

FROM alpine:3.23
RUN apk add --no-cache ca-certificates
COPY --from=build /forgejo-runner-k8s /usr/local/bin/forgejo-runner-k8s
