name: Build and push container images

on:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  build-images:
    runs-on: docker
    steps:
      - uses: https://data.forgejo.org/actions/checkout@v6

      - uses: https://data.forgejo.org/docker/setup-buildx-action@v4

      - name: Login to code.forgejo.org
        uses: https://data.forgejo.org/docker/login-action@v4
        with:
          registry: code.forgejo.org
          username: ${{ vars.USERNAME }}
          password: ${{ secrets.CODEBERG_TOKEN }}

      - name: Login to git.erwanleboucher.dev
        uses: https://data.forgejo.org/docker/login-action@v4
        with:
          registry: git.erwanleboucher.dev
          username: ${{ vars.USERNAME }}
          password: ${{ secrets.OWNER_PACKAGE_SECRET }}

      - name: Compute image metadata
        id: meta
        uses: https://data.forgejo.org/docker/metadata-action@v6
        with:
          images: |
            code.forgejo.org/${{ vars.USERNAME }}/runner-k8s-plugin
            git.erwanleboucher.dev/${{ vars.USERNAME }}/runner-k8s-plugin
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha,format=long
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Build and push (v1)
        uses: https://data.forgejo.org/docker/build-push-action@v7
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Compute v2 image metadata
        id: meta-v2
        uses: https://data.forgejo.org/docker/metadata-action@v6
        with:
          images: |
            code.forgejo.org/${{ vars.USERNAME }}/runner-k8s-plugin-v2
            git.erwanleboucher.dev/${{ vars.USERNAME }}/runner-k8s-plugin-v2
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha,format=long
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Build and push (v2)
        uses: https://data.forgejo.org/docker/build-push-action@v7
        with:
          context: .
          file: Dockerfile.v2
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta-v2.outputs.tags }}
          labels: ${{ steps.meta-v2.outputs.labels }}
